apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-03-03T07:07:41Z"
  labels:
    id: secret-handler
    red_ident: 9cf7a7c0-fdb2-4c35-9c13-c2a0bb52b4a9
    type: automatic
    uuid: 1428721e-8d1c-4c09-b5d6-afd79200c56a
  name: secret-handler
  namespace: moon
  resourceVersion: "38343"
  uid: ff293f21-fbf1-4fdd-bc08-2d70ef04d615
spec:
  containers:
  - args:
    - bash
    - -c
    - sleep 2d
    env:
    - name: SECRET_KEY_1
      value: '>8$kH#kj..i8}HImQd{'
    - name: SECRET_KEY_2
      value: IO=a4L/XkRdvN8jM=Y+
    - name: SECRET_KEY_3
      value: -7PA0_Z]>{pwa43r)__
    image: bash:5.0.11
    imagePullPolicy: IfNotPresent
    name: secret-handler
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /cache1
      name: cache-volume1
    - mountPath: /cache2
      name: cache-volume2
    - mountPath: /cache3
      name: cache-volume3
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-744qt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cluster1-worker1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: cache-volume1
  - emptyDir: {}
    name: cache-volume2
  - emptyDir: {}
    name: cache-volume3
  - name: kube-api-access-744qt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace