apiVersion: batch/v1
kind: Job
metadata:
  name: neb-new-job
spec: 
  template:
    metadata:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep 2 && echo done
        image: busybox:1.31.0
        name: neb-new-job
