CODE_CHANGES = getGitChanges()

pipeline {

    agent any

    stages {

        stage("build") {
            when {
                expression {
                    BRANCH_NAME == 'dev' && CODE_CHANGES == true
                }
            }
            steps {
                echo 'POLLA building the application...'
            }
        }
        stage("test") {

            steps {
                echo 'TeStInG the application...'
            }
        }
        stage("deploy") {

            steps {
                echo 'Deplooooying the application'
            }
        }
    }
}