apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"api","namespace":"venus"},"spec":{"replicas":2,"selector":{"matchLabels":{"id":"api"}},"template":{"metadata":{"labels":{"id":"api"}},"spec":{"containers":[{"image":"httpd:2.4.41-alpine","name":"python"}]}}}}
  creationTimestamp: "2022-01-05T13:51:12Z"
  generation: 1
  name: api
  namespace: venus
  resourceVersion: "5160"
  uid: 6bd14447-fe78-4d50-8ecd-b476d762fe92
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      id: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: api
    spec:
      containers:
      - image: httpd:2.4.41-alpine
        imagePullPolicy: IfNotPresent
        name: python
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-01-05T13:53:06Z"
    lastUpdateTime: "2022-01-05T13:53:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-05T13:51:12Z"
    lastUpdateTime: "2022-01-05T13:53:06Z"
    message: ReplicaSet "api-6d99f75ff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
