apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: venus
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      id: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: api
    spec:
      containers:
      - image: httpd:2.4.41-alpine
        name: python