apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"frontend","namespace":"venus"},"spec":{"replicas":5,"selector":{"matchLabels":{"id":"frontend"}},"template":{"metadata":{"labels":{"id":"frontend"}},"spec":{"containers":[{"image":"nginx:1.17.3-alpine","name":"nginx"}]}}}}
  creationTimestamp: "2022-01-05T13:51:12Z"
  generation: 1
  name: frontend
  namespace: venus
  resourceVersion: "5344"
  uid: 3dd22451-aac6-458e-9361-d6e24ae08d1f
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      id: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: frontend
    spec:
      containers:
      - image: nginx:1.17.3-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2022-01-05T13:53:22Z"
    lastUpdateTime: "2022-01-05T13:53:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-05T13:51:13Z"
    lastUpdateTime: "2022-01-05T13:53:26Z"
    message: ReplicaSet "frontend-556db8f554" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
