apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: venus
spec:
  replicas: 5
  selector:
    matchLabels:
      id: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: frontend
    spec:
      containers:
      - image: nginx:1.17.3-alpine
        imagePullPolicy: IfNotPresent
        name: nginx