apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"jupiter-crew-deploy","namespace":"jupiter"},"spec":{"replicas":1,"selector":{"matchLabels":{"id":"jupiter-crew"}},"template":{"metadata":{"labels":{"id":"jupiter-crew"}},"spec":{"containers":[{"image":"httpd:2.4.41-alpine","name":"apache"}]}}}}
  creationTimestamp: "2022-01-05T13:51:10Z"
  generation: 1
  name: jupiter-crew-deploy
  namespace: jupiter
  resourceVersion: "4968"
  uid: 904dd7d0-d301-44b6-a1d5-d7a21399d3e9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      id: jupiter-crew
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: jupiter-crew
    spec:
      containers:
      - image: httpd:2.4.41-alpine
        imagePullPolicy: IfNotPresent
        name: apache
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-05T13:52:36Z"
    lastUpdateTime: "2022-01-05T13:52:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-05T13:51:10Z"
    lastUpdateTime: "2022-01-05T13:52:36Z"
    message: ReplicaSet "jupiter-crew-deploy-57bc46b86b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
