apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"jupiter-crew-svc","namespace":"jupiter"},"spec":{"ports":[{"name":"8080-80","port":8080,"protocol":"TCP","targetPort":80}],"selector":{"id":"jupiter-crew"},"type":"ClusterIP"}}
  creationTimestamp: "2022-01-05T13:51:07Z"
  name: jupiter-crew-svc
  namespace: jupiter
  resourceVersion: "3969"
  uid: 3b0d2673-5cd0-4859-801e-da5f8cc2fa69
spec:
  clusterIP: 10.104.58.53
  clusterIPs:
  - 10.104.58.53
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    id: jupiter-crew
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
