apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupiter-crew-deploy
  namespace: jupiter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      id: jupiter-crew
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: jupiter-crew
    spec:
      containers:
      - image: httpd:2.4.41-alpine
        imagePullPolicy: IfNotPresent
        name: apache