apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"manager-api-svc"},"name":"manager-api-svc","namespace":"mars"},"spec":{"ports":[{"name":"4444-80","port":4444,"protocol":"TCP","targetPort":80}],"selector":{"id":"manager-api-deployment"},"type":"ClusterIP"}}
  creationTimestamp: "2022-01-05T13:51:07Z"
  labels:
    app: manager-api-svc
  name: manager-api-svc
  namespace: mars
  resourceVersion: "3973"
  uid: 4549a0c5-15b2-4faa-a61c-fd02e35d24a7
spec:
  clusterIP: 10.106.195.226
  clusterIPs:
  - 10.106.195.226
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 4444-80
    port: 4444
    protocol: TCP
    targetPort: 80
  selector:
    id: manager-api-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
