apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"id":"manager-api-deployment"},"name":"manager-api-deployment","namespace":"mars"},"spec":{"replicas":4,"selector":{"matchLabels":{"id":"manager-api-pod"}},"strategy":{},"template":{"metadata":{"labels":{"id":"manager-api-pod"}},"spec":{"containers":[{"image":"nginx:1.17.3-alpine","name":"nginx"}]}}}}
  creationTimestamp: "2022-01-05T13:51:10Z"
  generation: 1
  labels:
    id: manager-api-deployment
  name: manager-api-deployment
  namespace: mars
  resourceVersion: "5011"
  uid: b5f855ae-078e-4ac5-8016-6b298afca636
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      id: manager-api-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        id: manager-api-pod
    spec:
      containers:
      - image: nginx:1.17.3-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2022-01-05T13:52:38Z"
    lastUpdateTime: "2022-01-05T13:52:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-05T13:51:10Z"
    lastUpdateTime: "2022-01-05T13:52:39Z"
    message: ReplicaSet "manager-api-deployment-5c9b85bc4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
