apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    id: manager-api-deployment
  name: manager-api-deployment
  namespace: mars
spec:
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      id: manager-api-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        id: manager-api-pod
    spec:
      containers:
      - image: nginx:1.17.3-alpine
        name: nginx
