apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "6"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kubernetes.io/change-cause":"kubectl edit deployment api-new-c32 --namespace=neptune"},"labels":{"id":"api-new-c32"},"name":"api-new-c32","namespace":"neptune"},"spec":{"replicas":3,"selector":{"matchLabels":{"id":"api-new-c32"}},"template":{"metadata":{"labels":{"id":"api-new-c32"}},"spec":{"containers":[{"image":"ngnix:1.16.3","name":"nginx"}]}}}}
      kubernetes.io/change-cause: kubectl edit deployment api-new-c32 --namespace=neptune
    creationTimestamp: "2022-01-05T13:51:11Z"
    generation: 6
    labels:
      id: api-new-c32
    name: api-new-c32
    namespace: neptune
    resourceVersion: "14040"
    uid: 2d6b6e48-00be-4dfb-87b8-180bbb8a0a90
  spec:
    progressDeadlineSeconds: 600
    replicas: 4
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        id: api-new-c32
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          id: api-new-c32
      spec:
        containers:
        - image: nginx:1.16.3
          imagePullPolicy: IfNotPresent
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2022-01-05T13:53:05Z"
      lastUpdateTime: "2022-01-05T13:53:05Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-03-02T21:43:58Z"
      lastUpdateTime: "2022-03-02T21:44:15Z"
      message: ReplicaSet "api-new-c32-fdfb8fff4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 6
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
