apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      id: earth-2x3-api-svc
    name: earth-2x3-api-svc
    namespace: earth
  spec:
    clusterIP: 10.106.179.41
    clusterIPs:
    - 10.106.179.41
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 4546-80
      port: 4546
      protocol: TCP
      targetPort: 80
    selector:
      id: earth-2x3-api
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      id: earth-2x3-web-svc
    name: earth-2x3-web-svc
    namespace: earth
    resourceVersion: "3961"
    uid: 1c441288-3a8c-4b28-a4dc-746d387df1b8
  spec:
    clusterIP: 10.96.93.174
    clusterIPs:
    - 10.96.93.174
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 4545-80
      port: 4545
      protocol: TCP
      targetPort: 80
    selector:
      id: earth-2x3-web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1

  kind: Service
  metadata:
    labels:
      id: earth-3cc-web
    name: earth-3cc-web
    namespace: earth
    resourceVersion: "3965"
    uid: 61c303a6-4973-4849-bc25-d5a8cddf8770
  spec:
    clusterIP: 10.110.90.233
    clusterIPs:
    - 10.110.90.233
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 6363-80
      port: 6363
      protocol: TCP
      targetPort: 80
    selector:
      id: earth-3cc-web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
